FORMAT: 1A
HOST: https://polls.apiblueprint.org/

# buda-trans

Polls is a simple API allowing consumers to view polls and vote in them.

## Sessions [/sessions]

### Create new session [POST]

+ Request (application/json)

        {
            "email": "example@example.com",
            "password": "bestPa55W0rd3ver"
        }

+ Response 200 (application/json)

        {
            "data": {
                "user": {
                    "email": "example@example.com",
                    "authentication_token": "smnozAAbYnEX2xVRfS5R"
                }
            }
        }