export const SIGNIN_ATTEMPT = 'SIGNIN_ATTEMPT'
export const SIGNIN_FAIL = 'SIGNIN_FAIL'
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS'
export const SIGNOUT = 'SIGNOUT'

export const SIGNUP_ATTEMPT = 'SIGNUP_ATTEMPT'
export const SIGNUP_FAIL = 'SIGNUP_FAIL'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'

export const BUDA_SIGNIN_ATTEMPT = 'BUDA_SIGNIN_ATTEMPT'
export const BUDA_SIGNIN_FAIL = 'BUDA_SIGNIN_FAIL'
export const BUDA_SIGNIN_SUCCESS = 'BUDA_SIGNIN_SUCCESS'
export const BUDA_SIGNOUT = 'BUDA_SIGNOUT'

export const MUTATE_PERFIL_COMPONENT = 'MUTATE_PERFIL_COMPONENT'

export const SUCCESS_ALERT = 'SUCCESS_ALERT'
export const ERROR_ALERT = 'ERROR_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'