export const SIGNIN_ATTEMPT = 'SIGNIN_ATTEMPT'
export const SIGNIN_FAIL = 'SIGNIN_FAIL'
export const SIGNIN_SUCCESS = 'SIGNIN_SUCCESS'
export const SIGNOUT = 'SIGNOUT'

export const SIGNUP_ATTEMPT = 'SIGNUP_ATTEMPT'
export const SIGNUP_FAIL = 'SIGNUP_FAIL'
export const SIGNUP_SUCCESS = 'SIGNUP_SUCCESS'

export const BUDA_SIGNIN_ATTEMPT = 'BUDA_SIGNIN_ATTEMPT'
export const BUDA_SIGNIN_FAIL = 'BUDA_SIGNIN_FAIL'
export const BUDA_SIGNIN_SUCCESS = 'BUDA_SIGNIN_SUCCESS'
export const BUDA_SIGNOUT = 'BUDA_SIGNOUT'

export const GET_QUOTATION_ATTEMP = 'GET_QUOTATION_ATTEMP'
export const GET_QUOTATION_FAIL = 'GET_QUOTATION_FAIL'
export const GET_QUOTATION_SUCCESS = 'GET_QUOTATION_SUCCESS'

export const GET_USER_BALANCE_ATTEMP = 'GET_USER_BALANCE_ATTEMP'
export const GET_USER_BALANCE_FAIL = 'GET_USER_BALANCE_FAIL'
export const GET_USER_BALANCE_SUCCESS = 'USERBALANCE_SUCCESS'

export const SEND_PAYMENT_ATTEMP = 'SEND_PAYMENT_ATTEMP'
export const SEND_PAYMENT_FAIL = 'SEND_PAYMENT_FAIL'
export const SEND_PAYMENT_SUCCESS = 'SEND_PAYMENT_SUCCESS'

export const MUTATE_PROFILE_COMPONENT = 'MUTATE_PROFILE_COMPONENT'

export const SUCCESS_ALERT = 'SUCCESS_ALERT'
export const ERROR_ALERT = 'ERROR_ALERT'
export const CLEAR_ALERT = 'CLEAR_ALERT'