default: &default
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
  splitwise_consumer_key: <%= ENV["SPLITWISE_CONSUMER_KEY"] %>
  splitwise_consumer_secret: <%= ENV["SPLITWISE_CONSUMER_SECRET"] %>
  splitwise_token_url: <%= ENV["SPLITWISE_TOKEN_URL"] %>
  splitwise_access_token_url: <%= ENV["SPLITWISE_ACCESS_TOKEN_URL"] %>
  splitwise_authorize_url: <%= ENV["SPLITWISE_AUTHORIZE_URL"] %>
  splitwise_callback_url: <%= ENV["SPLITWISE_CALLBACK_URL"] %>
  splitwise_base_site: <%= ENV["SPLITWISE_BASE_SITE"] %>

  firebase_credentials:  <%= ENV["FIREBASE_CREDENTIALS"] %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
