default: &default
  secret_key_base: <%= ENV.fetch("SECRET_KEY_BASE") %>
  splitwise_consumer_key: <%= ENV.fetch("SPLITWISE_CONSUMER_KEY") %>
  splitwise_consumer_secret: <%= ENV.fetch("SPLITWISE_CONSUMER_SECRET") %>
  splitwise_token_url: <%= ENV.fetch("SPLITWISE_TOKEN_URL") %>
  splitwise_access_token_url: <%= ENV.fetch("SPLITWISE_ACCESS_TOKEN_URL") %>
  splitwise_authorize_url: <%= ENV.fetch("SPLITWISE_AUTHORIZE_URL") %>
  splitwise_callback_url: <%= ENV.fetch("SPLITWISE_CALLBACK_URL") %>
  splitwise_base_site: <%= ENV.fetch("SPLITWISE_BASE_SITE") %>
  buda_payment_simulation: <%= ENV.fetch("INVOICE_PAYMENT_SIMULATION") %>
  firebase_credentials: <%= ENV.fetch("FIREBASE_CREDENTIALS") %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
